### PR TITLE
Fixed missing method "enc"

### PR DESCRIPTION
**Pull request by jeffreysharris**
Corrected issue # 7. Updated method to “encryption”, per update to
mdp/gibberish.

Also, latest version of mdp/gibberish no longer uses CBC encryption, but
the JS library mdp/gibberish-aes does. Updated template to specifically
call CBC encryption, otherwise decryption always fails.

### CODE REVIEW

**Comment by macandcheese** [comment]
Is it possible to accept this PR into the gem? Would be great to use this functionality. Thanks!

**Comment by telephant00** [comment]
@jeffreysharris Thank you for the PR! @ahoward please merge!

**Comment by forcefulhandshake** [comment]
Amazing @jeffreysharris would be great to merge this in @ahoward Thanks guys!

**Comment by cbetta** [comment]
Can we just get this merged in @ahoward ?

**Pull request merged**
